export default {
  CREATE_EMPTY_GRID: 'CREATE_EMPTY_GRID',
  REGISTER_CONTEXT: 'REGISTER_CONTEXT',
  CLICK_GRID: 'CLICK_GRID',
  UPDATE_GRID: 'UPDATE_GRID',
  RESET_GRID: 'RESET_GRID',
  TOGGLE_CELL: 'TOGGLE_CELL',
  COPY_GRID: 'COPY_GRID',
  NEXT_FRAME: 'NEXT_FRAME',
  PREV_FRAME: 'PREV_FRAME',
  CHANGE_ROWS: 'CHANGE_ROWS',
  CHANGE_COLUMNS: 'CHANGE_COLUMNS',
  TOGGLE_PLAY: 'TOGGLE_PLAY',
  CHANGE_CELL_SIZE: 'CHANGE_CELL_SIZE',
  CHANGE_CELL_COLOR: 'CHANGE_CELL_COLOR',
  CHANGE_FPS: 'CHANGE_FPS'
};
